- name: Playbook to deploy S3 service
  hosts: localhost
  gather_facts: false
  connection: local
  roles:
  - role: ansible.kubernetes-modules
    install_python_requirements: no
  - role: ansibleplaybookbundle.asb-modules
  - role: provision-gluster-s3-apb
    playbook_debug: false
  vars:
    action: provision
    #cluster: glusterfs
